appname: "Xtreme Nmap Parser"
version: "1.0.2"

nmap_file_extension: ".xml"

xlsx:
  sheet_name: "Nmap Scan Results"
  headers_color: "#9D2911"
  headers_text_color: "#FFFFFF"
  table_style: "Table Style Medium 16"
  headers_default: [ 'Hostname',
              'IP',
              'State',
              'Port',
              'Protocol',
              'State Port',
              'Service Name',
              'Product',
              'Version',
              'Extrainfo']
  headers_all: [ 'Hostname',
              'IP',
              'State',
              'Port',
              'Protocol',
              'State Port',
              'Service Name',
              'Product',
              'Version',
              'Extrainfo',
              'Scripts']