app:
  name: "Xtreme Nmap Parser"
  version: "1.0.4"

nmap_file_extension: ".xml"

xlsx:
  sheet:
    name: "Nmap Scan Results"
  table:
    style: "Table Style Medium 16"
  header:
    color: "#9D2911"
    text:
      color: "#FFFFFF"
  columns:
    default: [ 'Hostname',
              'IP',
              'State',
              'Port',
              'Protocol',
              'State Port',
              'Service Name',
              'Product',
              'Version',
              'Extrainfo']
    all: [ 'Hostname',
              'IP',
              'State',
              'Port',
              'Protocol',
              'State Port',
              'Service Name',
              'Product',
              'Version',
              'Extrainfo',
              'Scripts']